[Settings]

ID = "busrouter-sg"

[context.production]
  publish = "dist/"
  command = "npm run build"

[context.v1]
  publish = ""
  command = ""

[[redirects]]
  from = "https://next.busrouter.sg/*"
  to = "https://busrouter.sg/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://next.busrouter.sg/"
  to = "https://busrouter.sg/"
  status = 301
  force = true